spring:
  application:
    name: grid
  datasource:
    url: jdbc:postgresql://localhost:5432/grid_db
    username: grid_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
